[SVCDEV-1509] JSXElement/JSXFragment children 내 공백 trim 하는 로직 수정
LenditKr/recast pull request #5
Opened 2022-11-11 08:16 UTC by donald-lendit

## 설명

기존 조건 + @
- leading space 에 개행이 있다면(공백은 볼 필요 없음) trimstart
- trailing space 에 개행이 있다면(공백은 볼 필요 없음) trimend

## 참고

- Related: [Jira](https://lendit.atlassian.net/browse/SVCDEV-1509)

2022-11-11 08:17 UTC, mark-lendit requested changes

2022-11-11 08:17 UTC, mark-lendit commented on lib/printer.ts
> +            ) {
동일한 조건이 1310라인에 있습니다.

2022-11-11 08:19 UTC, donald-lendit commented on lib/printer.ts
> +            ) {
죄송합니다. master 푸시에 멘탈이 나갔네요..ㅠㅠ

2022-11-11 08:28 UTC, mark-lendit requested changes

2022-11-11 08:28 UTC, mark-lendit commented on lib/printer.ts
> +              if (/(^[\n|\s]*)(\S+)/.test(v)) {
해당 정규표현식은 아래 문자열도 통과가 됩니다.
```
"             ASDF"
```
개행이 포함된 경우에만 공백을 제거해야 합니다.

2022-11-14 02:41 UTC, mark-lendit approved these changes
LGTM!

2022-11-14 02:50 UTC, merged